export enum WsRquestMessageType {
    OPEN_WALLET = "OPEN_WALLET",
    CREATE_WALLET = "CREATE_WALLET",
    CREATE_WALLET_FROM_KEYS = "CREATE_WALLET_FROM_KEYS",
    RESCAN_BC = "RESCAN_BC",
    CLOSE_WALLET = "CLOSE_WALLET",
    SEND_CASH = "SEND_CASH",
    SEND_TOKEN = "SEND_TOKEN",
    CREATE_ACCOUNT = "CREATE_ACCOUNT",
    REMOVE_ACCOUNT = "REMOVE_ACCOUNT",
    RECOVER_ACCOUNT = "RECOVER_ACCOUNT",
    EDIT_ACCOUNT = "EDIT_ACCOUNT",
    CREATE_OFFER = "CREATE_OFFER",
    EDIT_OFFER = "EDIT_OFFER",
    PURCHASE_OFFER = "PURCHASE_OFFER",
    GIVE_FEEDBACK = "GIVE_FEEDBACK",
    GET_FEEDBACKS = "GET_FEEDBACKS",
    CHECK_TX_PROOF = "CHECK_TX_PROOF",
    HISTORY = "HISTORY",
    STAKE_TOKENS = "STAKE_TOKENS",
    UNSTAKE_TOKENS = "UNSTAKE_TOKENS",

}

export enum WsMessageValidationStatus {
    OK = "OK",
    ERROR = "ERROR"
}
