version: '3.7'
services:

  safex-big-box-appserver:
    container_name: safex-big-box-appserver
    image: safexninja/safex-big-box-nodejs:1.0
    # image: safex-big-box-appserver:1.0
    # build:
    #    context: docker/nodejs
    stdin_open: true
    working_dir: /home/docker/safex
    command: bash -c "sudo chown -R docker /home/docker/safex && ./run-app-server.sh"
    volumes:
      - ./src:/home/docker/safex/src
      - ./package.json:/home/docker/safex/package.json
      - ./tsconfig.json:/home/docker/safex/tsconfig.json
      - ./webpack.config.js:/home/docker/safex/webpack.config.js
    environment:
      - PORT=4437
    depends_on:
      - safex-big-box-apiserver
    expose:
      - 4437

  safex-big-box-apiserver:
    container_name: safex-big-box-apiserver
    image: safexninja/safex-big-box-nodejs:1.0
    # image: safex-big-box-apiserver:1.0
    # build:
    #    context: docker/nodejs
    stdin_open: true
    working_dir: /home/docker/safex
    command: bash -c "sudo chown -R docker /home/docker/safex && ./run-api-server.sh"
    volumes:
      - ./src:/home/docker/safex/src
      - ./package.json:/home/docker/safex/package.json
      - ./tsconfig.json:/home/docker/safex/tsconfig.json
    environment:
      - LOGLEVEL=WARN
      - NETWORK=${NETWORK}
      - DAEMON_ADDRESS=http://safex-big-box-daemon
      - DAEMON_PORT=${DAEMON_PORT}
      - DB_HOST=safex-big-box-mongodb
      - DB_NAME=${MONGODB_DATABASE}
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_PORT=${MONGODB_PORT}
      - PORT=4436
    depends_on:
      - safex-big-box-daemon
      - safex-big-box-mongodb
      - safex-big-box-walletserver
    expose:
      - 4436

  safex-big-box-walletserver:
    container_name: safex-big-box-walletserver
    image: safexninja/safex-big-box-nodejs:1.0
    # image: safex-big-box-walletserver:1.0
    # build: 
    #    context: docker/nodejs
    stdin_open: true
    working_dir: /home/docker/safex
    command: bash -c "sudo chown -R docker /home/docker/safex && sudo chown -R docker /home/docker/files && ./run-wallet-server.sh"
    volumes:
      - ./src:/home/docker/safex/src
      - ./package.json:/home/docker/safex/package.json
      - ./tsconfig.json:/home/docker/safex/tsconfig.json
      - ${FILE_STORE_DIR}:/home/docker/files
    environment:
      - LOGLEVEL=INFO
      - NETWORK=${NETWORK}
      - DAEMON_ADDRESS=http://safex-big-box-daemon
      - DAEMON_PORT=${DAEMON_PORT}
      - FILE_STORE_DIR=/home/docker/files
      - WALLET_INTACTIVE_TIMEOUT=3000000
      - DB_HOST=safex-big-box-mongodb
      - DB_NAME=${MONGODB_DATABASE}
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_PORT=${MONGODB_PORT}
      - PORT=4435
    depends_on:
      - safex-big-box-daemon
      - safex-big-box-mongodb
    expose:
      - 4435

  safex-big-box-mongodb:
    container_name: safex-big-box-mongodb
    image: safex-big-box-mongodb:1.0
    build: 
       context: docker/mongodb
    volumes:
      - ${MONGODB_DIR}:/data/db
      - ./docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --port ${MONGODB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    expose:
      - ${MONGODB_PORT}

  safex-big-box-explorer:
    container_name: safex-big-box-explorer
    image: safexninja/safex-binaries:1.0
    # image: safex-big-box-binaries:1.0
    # build: 
      #  context: docker/safex_binaries
    stdin_open: true
    working_dir: /home/docker/explorer
    command: ["./wait-for-it.sh", "safex-big-box-daemon:${DAEMON_PORT}", "--", "bash", "-c", "sudo ./safex-explorer ${NETWORK_FLAG} -b /home/docker/.safex/${LMDB_DIR} -d http://safex-big-box-daemon:${DAEMON_PORT} --bind-host 0.0.0.0 --enable-autorefresh-option 1 --no-blocks-on-index 20"]
    restart: on-failure
    volumes:
      - ${LOCAL_BC_DATA_DIR}/.safex:/home/docker/.safex
    depends_on:
      - safex-big-box-daemon
    expose:
      - 8081

  safex-big-box-daemon:
    container_name: safex-big-box-daemon
    image: safexninja/safex-binaries:1.0
    # image: safex-big-box-binaries:1.0
    # build: 
      #  context: docker/safex_binaries
    working_dir: /home/docker/daemon
    command: bash -c "sudo ./safexd ${NETWORK_FLAG} --rpc-bind-ip 0.0.0.0 --out-peers=20 --data-dir=/home/docker/.safex --confirm-external-bind --restricted-rpc"
    tty: true
    volumes:
      - ${LOCAL_BC_DATA_DIR}/.safex:/home/docker/.safex
    expose:
      - ${DAEMON_PORT}

  safex-big-box-nginx:
    container_name: safex-big-box-nginx
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/loader.html:/usr/share/nginx/html/loader.html
      - ./nginx/bigboxlogo.png:/usr/share/nginx/html/bigboxlogo.png
      - ./explorer/styling/images:/usr/share/nginx/html/images
      - ./explorer/styling/css:/usr/share/nginx/html/css
      - ./explorer/styling/favicon.png:/usr/share/nginx/html/favicon.png
      - ./cert:/usr/cert
    depends_on:
      - safex-big-box-explorer
      - safex-big-box-apiserver
      - safex-big-box-walletserver
      - safex-big-box-appserver
    ports:
      - 443:443

networks:
  default:
    name: safex-big-box
