FROM electronuserland/builder:16-wine-mono

RUN apt-get update -y 

RUN apt-get install -y \
    build-essential \ 
    cmake \
    make \
    libboost-all-dev \
    miniupnpc \
    graphviz \
    doxygen \
    pkg-config \
    libcurl4-openssl-dev \
    libgtest-dev \
    libreadline-dev \
    libsodium-dev \
    libzmq3-dev \
    libpcsclite-dev \
    libunwind8-dev \
    libssl-dev \ 
    libunbound-dev \ 
    libminiupnpc-dev \
    liblzma-dev \ 
    libldns-dev \
    libexpat1-dev \
    libprotobuf-dev \
    nano 
    
LABEL author="Safex.Ninja"


