export const countries = [
    {country:"AF",label:"Afghanistan"},
    {country:"AX",label:"Åland Islands"},
    {country:"AL",label:"Albania"},
    {country:"DZ",label:"Algeria"},
    {country:"AS",label:"American Samoa"},
    {country:"AD",label:"Andorra"},
    {country:"AO",label:"Angola"},
    {country:"AI",label:"Anguilla"},
    {country:"AQ",label:"Antarctica"},
    {country:"AG",label:"Antigua and Barbuda"},
    {country:"AR",label:"Argentina"},
    {country:"AM",label:"Armenia"},
    {country:"AW",label:"Aruba"},
    {country:"AU",label:"Australia"},
    {country:"AT",label:"Austria"},
    {country:"AZ",label:"Azerbaijan"},
    {country:"BS",label:"Bahamas"},
    {country:"BH",label:"Bahrain"},
    {country:"BD",label:"Bangladesh"},
    {country:"BB",label:"Barbados"},
    {country:"BY",label:"Belarus"},
    {country:"BE",label:"Belgium"},
    {country:"BZ",label:"Belize"},
    {country:"BJ",label:"Benin"},
    {country:"BM",label:"Bermuda"},
    {country:"BT",label:"Bhutan"},
    {country:"BO",label:"Bolivia"},
    {country:"BQ",label:"Bonaire, Sint Eustatius and Saba"},
    {country:"BA",label:"Bosnia and Herzegovina"},
    {country:"BW",label:"Botswana"},
    {country:"BV",label:"Bouvet Island"},
    {country:"BR",label:"Brazil"},
    {country:"IO",label:"British Indian Ocean Territory"},
    {country:"BN",label:"Brunei"},
    {country:"BG",label:"Bulgaria"},
    {country:"BF",label:"Burkina Faso"},
    {country:"BI",label:"Burundi"},
    {country:"KH",label:"Cambodia"},
    {country:"CM",label:"Cameroon"},
    {country:"CA",label:"Canada"},
    {country:"CV",label:"Cape Verde"},
    {country:"KY",label:"Cayman Islands"},
    {country:"CF",label:"Central African Republic"},
    {country:"TD",label:"Chad"},
    {country:"CL",label:"Chile"},
    {country:"CN",label:"China"},
    {country:"CX",label:"Christmas Island"},
    {country:"CC",label:"Cocos (Keeling) Islands"},
    {country:"CO",label:"Colombia"},
    {country:"KM",label:"Comoros"},
    {country:"CG",label:"Congo, Republic of the (Brazzaville)"},
    {country:"CD",label:"Congo, the Democratic Republic of the (Kinshasa)"},
    {country:"CK",label:"Cook Islands"},
    {country:"CR",label:"Costa Rica"},
    {country:"CI",label:"Côte d'Ivoire, Republic of"},
    {country:"HR",label:"Croatia"},
    {country:"CW",label:"Curaçao"},
    {country:"CU",label:"Cuba"},
    {country:"CY",label:"Cyprus"},
    {country:"CZ",label:"Czech Republic"},
    {country:"DK",label:"Denmark"},
    {country:"DJ",label:"Djibouti"},
    {country:"DM",label:"Dominica"},
    {country:"DO",label:"Dominican Republic"},
    {country:"EC",label:"Ecuador"},
    {country:"EG",label:"Egypt"},
    {country:"SV",label:"El Salvador"},
    {country:"GQ",label:"Equatorial Guinea"},
    {country:"ER",label:"Eritrea"},
    {country:"EE",label:"Estonia"},
    {country:"ET",label:"Ethiopia"},
    {country:"FK",label:"Falkland Islands (Islas Malvinas)"},
    {country:"FO",label:"Faroe Islands"},
    {country:"FJ",label:"Fiji"},
    {country:"FI",label:"Finland"},
    {country:"FR",label:"France"},
    {country:"GF",label:"French Guiana"},
    {country:"PF",label:"French Polynesia"},
    {country:"TF",label:"French Southern and Antarctic Lands"},
    {country:"GA",label:"Gabon"},
    {country:"GM",label:"Gambia, The"},
    {country:"GE",label:"Georgia"},
    {country:"DE",label:"Germany"},
    {country:"GH",label:"Ghana"},
    {country:"GI",label:"Gibraltar"},
    {country:"GR",label:"Greece"},
    {country:"GL",label:"Greenland"},
    {country:"GD",label:"Grenada"},
    {country:"GP",label:"Guadeloupe"},
    {country:"GU",label:"Guam"},
    {country:"GT",label:"Guatemala"},
    {country:"GG",label:"Guernsey"},
    {country:"GN",label:"Guinea"},
    {country:"GW",label:"Guinea-Bissau"},
    {country:"GY",label:"Guyana"},
    {country:"HT",label:"Haiti"},
    {country:"HM",label:"Heard Island and McDonald Islands"},
    {country:"VA",label:"Holy See (Vatican City)"},
    {country:"HN",label:"Honduras"},
    {country:"HK",label:"Hong Kong"},
    {country:"HU",label:"Hungary"},
    {country:"IS",label:"Iceland"},
    {country:"IN",label:"India"},
    {country:"ID",label:"Indonesia"},
    {country:"IQ",label:"Iraq"},
    {country:"IR",label:"Iran, Islamic Republic of"},
    {country:"IE",label:"Ireland"},
    {country:"IM",label:"Isle of Man"},
    {country:"IL",label:"Israel"},
    {country:"IT",label:"Italy"},
    {country:"JM",label:"Jamaica"},
    {country:"JP",label:"Japan"},
    {country:"JE",label:"Jersey"},
    {country:"JO",label:"Jordan"},
    {country:"KZ",label:"Kazakhstan"},
    {country:"KE",label:"Kenya"},
    {country:"KI",label:"Kiribati"},
    {country:"KP",label:"Korea, Democratic People's Republic of"},
    {country:"KR",label:"Korea, Republic of"},
    {country:"XK",label:"Kosovo"},
    {country:"KW",label:"Kuwait"},
    {country:"KG",label:"Kyrgyzstan"},
    {country:"LA",label:"Laos"},
    {country:"LV",label:"Latvia"},
    {country:"LB",label:"Lebanon"},
    {country:"LS",label:"Lesotho"},
    {country:"LR",label:"Liberia"},
    {country:"LY",label:"Libya"},
    {country:"LI",label:"Liechtenstein"},
    {country:"LT",label:"Lithuania"},
    {country:"LU",label:"Luxembourg"},
    {country:"MO",label:"Macao"},
    {country:"MK",label:"Macedonia, Republic of"},
    {country:"MG",label:"Madagascar"},
    {country:"MW",label:"Malawi"},
    {country:"MY",label:"Malaysia"},
    {country:"MV",label:"Maldives"},
    {country:"ML",label:"Mali"},
    {country:"MT",label:"Malta"},
    {country:"MH",label:"Marshall Islands"},
    {country:"MQ",label:"Martinique"},
    {country:"MR",label:"Mauritania"},
    {country:"MU",label:"Mauritius"},
    {country:"YT",label:"Mayotte"},
    {country:"MX",label:"Mexico"},
    {country:"FM",label:"Micronesia, Federated States of"},
    {country:"MD",label:"Moldova"},
    {country:"MC",label:"Monaco"},
    {country:"MN",label:"Mongolia"},
    {country:"ME",label:"Montenegro"},
    {country:"MS",label:"Montserrat"},
    {country:"MA",label:"Morocco"},
    {country:"MZ",label:"Mozambique"},
    {country:"MM",label:"Myanmar"},
    {country:"NA",label:"Namibia"},
    {country:"NR",label:"Nauru"},
    {country:"NP",label:"Nepal"},
    {country:"NL",label:"Netherlands"},
    {country:"AN",label:"Netherlands Antilles"},
    {country:"NC",label:"New Caledonia"},
    {country:"NZ",label:"New Zealand"},
    {country:"NI",label:"Nicaragua"},
    {country:"NE",label:"Niger"},
    {country:"NG",label:"Nigeria"},
    {country:"NU",label:"Niue"},
    {country:"NF",label:"Norfolk Island"},
    {country:"MP",label:"Northern Mariana Islands"},
    {country:"NO",label:"Norway"},
    {country:"OM",label:"Oman"},
    {country:"PK",label:"Pakistan"},
    {country:"PW",label:"Palau"},
    {country:"PS",label:"Palestine, State of"},
    {country:"PA",label:"Panama"},
    {country:"PG",label:"Papua New Guinea"},
    {country:"PY",label:"Paraguay"},
    {country:"PE",label:"Peru"},
    {country:"PH",label:"Philippines"},
    {country:"PN",label:"Pitcairn"},
    {country:"PL",label:"Poland"},
    {country:"PT",label:"Portugal"},
    {country:"PR",label:"Puerto Rico"},
    {country:"QA",label:"Qatar"},
    {country:"RE",label:"Réunion"},
    {country:"RO",label:"Romania"},
    {country:"RU",label:"Russian Federation"},
    {country:"RW",label:"Rwanda"},
    {country:"BL",label:"Saint Barthélemy"},
    {country:"SH",label:"Saint Helena, Ascension and Tristan da Cunha"},
    {country:"KN",label:"Saint Kitts and Nevis"},
    {country:"LC",label:"Saint Lucia"},
    {country:"MF",label:"Saint Martin"},
    {country:"PM",label:"Saint Pierre and Miquelon"},
    {country:"VC",label:"Saint Vincent and the Grenadines"},
    {country:"WS",label:"Samoa"},
    {country:"SM",label:"San Marino"},
    {country:"ST",label:"Sao Tome and Principe"},
    {country:"SA",label:"Saudi Arabia"},
    {country:"SN",label:"Senegal"},
    {country:"RS",label:"Serbia"},
    {country:"CS",label:"Serbia and Montenegro"},
    {country:"SC",label:"Seychelles"},
    {country:"SL",label:"Sierra Leone"},
    {country:"SG",label:"Singapore"},
    {country:"SX",label:"Sint Maarten (Dutch part)"},
    {country:"SK",label:"Slovakia"},
    {country:"SI",label:"Slovenia"},
    {country:"SB",label:"Solomon Islands"},
    {country:"SO",label:"Somalia"},
    {country:"ZA",label:"South Africa"},
    {country:"GS",label:"South Georgia and South Sandwich Islands"},
    {country:"SS",label:"South Sudan"},
    {country:"ES",label:"Spain"},
    {country:"SJ",label:"Svalbard and Jan Mayen"},
    {country:"LK",label:"Sri Lanka"},
    {country:"SY",label:"Syrian Arab Republic"},
    {country:"SD",label:"Sudan"},
    {country:"SR",label:"Suriname"},
    {country:"SZ",label:"Swaziland"},
    {country:"SE",label:"Sweden"},
    {country:"CH",label:"Switzerland"},
    {country:"TW",label:"Taiwan"},
    {country:"TJ",label:"Tajikistan"},
    {country:"TZ",label:"Tanzania, United Republic of"},
    {country:"TH",label:"Thailand"},
    {country:"TL",label:"Timor-Leste"},
    {country:"TG",label:"Togo"},
    {country:"TK",label:"Tokelau"},
    {country:"TO",label:"Tonga"},
    {country:"TT",label:"Trinidad and Tobago"},
    {country:"TN",label:"Tunisia"},
    {country:"TR",label:"Turkey"},
    {country:"TM",label:"Turkmenistan"},
    {country:"TC",label:"Turks and Caicos Islands"},
    {country:"TV",label:"Tuvalu"},
    {country:"UG",label:"Uganda"},
    {country:"UA",label:"Ukraine"},
    {country:"AE",label:"United Arab Emirates"},
    {country:"GB",label:"United Kingdom"},
    {country:"US",label:"United States"},
    {country:"UM",label:"United States Minor Outlying Islands"},
    {country:"UY",label:"Uruguay"},
    {country:"UZ",label:"Uzbekistan"},
    {country:"VU",label:"Vanuatu"},
    {country:"VE",label:"Venezuela, Bolivarian Republic of"},
    {country:"VN",label:"Vietnam"},
    {country:"VG",label:"Virgin Islands, British"},
    {country:"VI",label:"Virgin Islands, U.S."},
    {country:"WF",label:"Wallis and Futuna"},
    {country:"EH",label:"Western Sahara"},
    {country:"YE",label:"Yemen"},
    {country:"ZM",label:"Zambia"},
    {country:"ZW",label:"Zimbabwe"}
];