// STAGENET
// export const STAKING_MINIMUM_TOKEN_AMOUNT = 10000 // amount
// const STAKING_MINIMUM_INTERVALS = 10 // number
// const STAKING_INTERVAL_PERIOD = 100 // blocks
// export const STAKING_MINIMUM_PERIOD = STAKING_MINIMUM_INTERVALS * STAKING_INTERVAL_PERIOD

// MAINNET
export const STAKING_MINIMUM_TOKEN_AMOUNT = 25000 // amount
export const STAKING_MINIMUM_INTERVALS = 8 // number
export const STAKING_INTERVAL_PERIOD = 1000 // blocks
export const STAKING_MINIMUM_PERIOD = STAKING_MINIMUM_INTERVALS * STAKING_INTERVAL_PERIOD